version: "3.8"
services:

  mongodb:
    image: mongo:latest
    container_name: backend-challenge-mongodb
    ports:
      - "27020:27017"
    volumes:
      - backend_challenge_mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_USERNAME: myusername
      MONGO_INITDB_PASSWORD: mypassword
    restart: unless-stopped

volumes:
  backend_challenge_mongodb_data:
